use std::fmt::Display;

use serde::{Deserialize, Serialize};
#[cfg(feature = "ssr")]
use sqlx::{sqlite::SqliteTypeInfo, Decode, Encode, Sqlite, Type};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[allow(clippy::upper_case_acronyms)]
pub enum Country {
    #[default]
    ESP,
    ALB,
    AND,
    AUT,
    BLR,
    BEL,
    BIH,
    BGR,
    HRV,
    CYP,
    CZE,
    DNK,
    EST,
    FIN,
    FRA,
    DEU,
    GRC,
    HUN,
    ISL,
    IRL,
    ITA,
    LVA,
    LIE,
    LTU,
    LUX,
    MLT,
    MDA,
    MCO,
    MNE,
    NLD,
    MKD,
    NOR,
    POL,
    PRT,
    ROU,
    RUS,
    SMR,
    SRB,
    SVK,
    SVN,
    SWE,
    CHE,
    UKR,
    GBR,
    VAT,
    ARG,
    BOL,
    BRA,
    CAN,
    CHL,
    COL,
    CRI,
    CUB,
    DOM,
    ECU,
    SLV,
    GTM,
    GUY,
    HTI,
    HND,
    JAM,
    MEX,
    NIC,
    PAN,
    PRY,
    PER,
    KNA,
    LCA,
    VCT,
    SUR,
    TTO,
    USA,
    URY,
    VEN,
    AFG,
    SAU,
    ARM,
    AZE,
    BHR,
    BGD,
    BTN,
    BRN,
    KHM,
    CHN,
    PRK,
    KOR,
    ARE,
    PHL,
    GEO,
    IND,
    IDN,
    IRN,
    IRQ,
    ISR,
    JPN,
    JOR,
    KAZ,
    KGZ,
    KWT,
    LAO,
    LBN,
    MYS,
    MDV,
    MNG,
    MMR,
    NPL,
    OMN,
    PAK,
    PSE,
    QAT,
    SGP,
    LKA,
    SYR,
    TWN,
    TJK,
    THA,
    TUR,
    TKM,
    UZB,
    VNM,
    YEM,
    DZA,
    AGO,
    BEN,
    BWA,
    BFA,
    BDI,
    CPV,
    CMR,
    CAF,
    TCD,
    COM,
    COG,
    COD,
    CIV,
    DJI,
    EGY,
    GNQ,
    ERI,
    SWZ,
    ETH,
    GAB,
    GMB,
    GHA,
    GIN,
    GNB,
    KEN,
    LSO,
    LBR,
    LBY,
    MDG,
    MWI,
    MLI,
    MRT,
    MUS,
    MAR,
    MOZ,
    NAM,
    NER,
    NGA,
    RWA,
    STP,
    SEN,
    SYC,
    SLE,
    SOM,
    ZAF,
    SSD,
    SDN,
    TZA,
    TGO,
    TUN,
    UGA,
    ZMB,
    ZWE,
    AUS,
    FJI,
    KIR,
    MHL,
    FSM,
    NRU,
    NZL,
    PLW,
    PNG,
    WSM,
    SLB,
    TON,
    TUV,
    VUT,
}

impl Display for Country {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let name = match self {
            Country::ESP => "España",
            Country::ALB => "Albania",
            Country::AND => "Andorra",
            Country::AUT => "Austria",
            Country::BLR => "Bielorrusia",
            Country::BEL => "Bélgica",
            Country::BIH => "Bosnia y Herzegovina",
            Country::BGR => "Bulgaria",
            Country::HRV => "Croacia",
            Country::CYP => "Chipre",
            Country::CZE => "Chequia",
            Country::DNK => "Dinamarca",
            Country::EST => "Estonia",
            Country::FIN => "Finlandia",
            Country::FRA => "Francia",
            Country::DEU => "Alemania",
            Country::GRC => "Grecia",
            Country::HUN => "Hungría",
            Country::ISL => "Islandia",
            Country::IRL => "Irlanda",
            Country::ITA => "Italia",
            Country::LVA => "Letonia",
            Country::LIE => "Liechtenstein",
            Country::LTU => "Lituania",
            Country::LUX => "Luxemburgo",
            Country::MLT => "Malta",
            Country::MDA => "Moldavia",
            Country::MCO => "Mónaco",
            Country::MNE => "Montenegro",
            Country::NLD => "Países Bajos",
            Country::MKD => "Macedonia del Norte",
            Country::NOR => "Noruega",
            Country::POL => "Polonia",
            Country::PRT => "Portugal",
            Country::ROU => "Rumanía",
            Country::RUS => "Rusia",
            Country::SMR => "San Marino",
            Country::SRB => "Serbia",
            Country::SVK => "Eslovaquia",
            Country::SVN => "Eslovenia",
            Country::SWE => "Suecia",
            Country::CHE => "Suiza",
            Country::UKR => "Ucrania",
            Country::GBR => "Reino Unido",
            Country::VAT => "Ciudad del Vaticano",
            Country::ARG => "Argentina",
            Country::BOL => "Bolivia",
            Country::BRA => "Brasil",
            Country::CAN => "Canadá",
            Country::CHL => "Chile",
            Country::COL => "Colombia",
            Country::CRI => "Costa Rica",
            Country::CUB => "Cuba",
            Country::DOM => "República Dominicana",
            Country::ECU => "Ecuador",
            Country::SLV => "El Salvador",
            Country::GTM => "Guatemala",
            Country::GUY => "Guyana",
            Country::HTI => "Haití",
            Country::HND => "Honduras",
            Country::JAM => "Jamaica",
            Country::MEX => "México",
            Country::NIC => "Nicaragua",
            Country::PAN => "Panamá",
            Country::PRY => "Paraguay",
            Country::PER => "Perú",
            Country::KNA => "San Cristóbal y Nieves",
            Country::LCA => "Santa Lucía",
            Country::VCT => "San Vicente y las Granadinas",
            Country::SUR => "Surinam",
            Country::TTO => "Trinidad y Tobago",
            Country::USA => "Estados Unidos",
            Country::URY => "Uruguay",
            Country::VEN => "Venezuela",
            Country::AFG => "Afganistán",
            Country::SAU => "Arabia Saudita",
            Country::ARM => "Armenia",
            Country::AZE => "Azerbaiyán",
            Country::BHR => "Baréin",
            Country::BGD => "Bangladés",
            Country::BTN => "Bután",
            Country::BRN => "Brunéi",
            Country::KHM => "Camboya",
            Country::CHN => "China",
            Country::PRK => "Corea del Norte",
            Country::KOR => "Corea del Sur",
            Country::ARE => "Emiratos Árabes Unidos",
            Country::PHL => "Filipinas",
            Country::GEO => "Georgia",
            Country::IND => "India",
            Country::IDN => "Indonesia",
            Country::IRN => "Irán",
            Country::IRQ => "Irak",
            Country::ISR => "Israel",
            Country::JPN => "Japón",
            Country::JOR => "Jordania",
            Country::KAZ => "Kazajistán",
            Country::KGZ => "Kirguistán",
            Country::KWT => "Kuwait",
            Country::LAO => "Laos",
            Country::LBN => "Líbano",
            Country::MYS => "Malasia",
            Country::MDV => "Maldivas",
            Country::MNG => "Mongolia",
            Country::MMR => "Myanmar (Birmania)",
            Country::NPL => "Nepal",
            Country::OMN => "Omán",
            Country::PAK => "Pakistán",
            Country::PSE => "Palestina",
            Country::QAT => "Catar",
            Country::SGP => "Singapur",
            Country::LKA => "Sri Lanka",
            Country::SYR => "Siria",
            Country::TWN => "Taiwán",
            Country::TJK => "Tayikistán",
            Country::THA => "Tailandia",
            Country::TUR => "Turquía",
            Country::TKM => "Turkmenistán",
            Country::UZB => "Uzbekistán",
            Country::VNM => "Vietnam",
            Country::YEM => "Yemen",
            Country::DZA => "Argelia",
            Country::AGO => "Angola",
            Country::BEN => "Benín",
            Country::BWA => "Botsuana",
            Country::BFA => "Burkina Faso",
            Country::BDI => "Burundi",
            Country::CPV => "Cabo Verde",
            Country::CMR => "Camerún",
            Country::CAF => "República Centroafricana",
            Country::TCD => "Chad",
            Country::COM => "Comoras",
            Country::COG => "República del Congo",
            Country::COD => "República Democrática del Congo",
            Country::CIV => "Costa de Marfil",
            Country::DJI => "Yibuti",
            Country::EGY => "Egipto",
            Country::GNQ => "Guinea Ecuatorial",
            Country::ERI => "Eritrea",
            Country::SWZ => "Esuatini",
            Country::ETH => "Etiopía",
            Country::GAB => "Gabón",
            Country::GMB => "Gambia",
            Country::GHA => "Ghana",
            Country::GIN => "Guinea",
            Country::GNB => "Guinea-Bisáu",
            Country::KEN => "Kenia",
            Country::LSO => "Lesoto",
            Country::LBR => "Liberia",
            Country::LBY => "Libia",
            Country::MDG => "Madagascar",
            Country::MWI => "Malaui",
            Country::MLI => "Malí",
            Country::MRT => "Mauritania",
            Country::MUS => "Mauricio",
            Country::MAR => "Marruecos",
            Country::MOZ => "Mozambique",
            Country::NAM => "Namibia",
            Country::NER => "Níger",
            Country::NGA => "Nigeria",
            Country::RWA => "Ruanda",
            Country::STP => "Santo Tomé y Príncipe",
            Country::SEN => "Senegal",
            Country::SYC => "Seychelles",
            Country::SLE => "Sierra Leona",
            Country::SOM => "Somalia",
            Country::ZAF => "Sudáfrica",
            Country::SSD => "Sudán del Sur",
            Country::SDN => "Sudán",
            Country::TZA => "Tanzania",
            Country::TGO => "Togo",
            Country::TUN => "Túnez",
            Country::UGA => "Uganda",
            Country::ZMB => "Zambia",
            Country::ZWE => "Zimbabue",
            Country::AUS => "Australia",
            Country::FJI => "Fiyi",
            Country::KIR => "Kiribati",
            Country::MHL => "Islas Marshall",
            Country::FSM => "Micronesia",
            Country::NRU => "Nauru",
            Country::NZL => "Nueva Zelanda",
            Country::PLW => "Palaos",
            Country::PNG => "Papúa Nueva Guinea",
            Country::WSM => "Samoa",
            Country::SLB => "Islas Salomón",
            Country::TON => "Tonga",
            Country::TUV => "Tuvalu",
            Country::VUT => "Vanuatu",
        };
        write!(f, "{name}")
    }
}

impl Country {
    pub const ALL: &'static [Self] = &[
        Country::ESP,
        Country::ALB,
        Country::AND,
        Country::AUT,
        Country::BLR,
        Country::BEL,
        Country::BIH,
        Country::BGR,
        Country::HRV,
        Country::CYP,
        Country::CZE,
        Country::DNK,
        Country::EST,
        Country::FIN,
        Country::FRA,
        Country::DEU,
        Country::GRC,
        Country::HUN,
        Country::ISL,
        Country::IRL,
        Country::ITA,
        Country::LVA,
        Country::LIE,
        Country::LTU,
        Country::LUX,
        Country::MLT,
        Country::MDA,
        Country::MCO,
        Country::MNE,
        Country::NLD,
        Country::MKD,
        Country::NOR,
        Country::POL,
        Country::PRT,
        Country::ROU,
        Country::RUS,
        Country::SMR,
        Country::SRB,
        Country::SVK,
        Country::SVN,
        Country::SWE,
        Country::CHE,
        Country::UKR,
        Country::GBR,
        Country::VAT,
        Country::ARG,
        Country::BOL,
        Country::BRA,
        Country::CAN,
        Country::CHL,
        Country::COL,
        Country::CRI,
        Country::CUB,
        Country::DOM,
        Country::ECU,
        Country::SLV,
        Country::GTM,
        Country::GUY,
        Country::HTI,
        Country::HND,
        Country::JAM,
        Country::MEX,
        Country::NIC,
        Country::PAN,
        Country::PRY,
        Country::PER,
        Country::KNA,
        Country::LCA,
        Country::VCT,
        Country::SUR,
        Country::TTO,
        Country::USA,
        Country::URY,
        Country::VEN,
        Country::AFG,
        Country::SAU,
        Country::ARM,
        Country::AZE,
        Country::BHR,
        Country::BGD,
        Country::BTN,
        Country::BRN,
        Country::KHM,
        Country::CHN,
        Country::PRK,
        Country::KOR,
        Country::ARE,
        Country::PHL,
        Country::GEO,
        Country::IND,
        Country::IDN,
        Country::IRN,
        Country::IRQ,
        Country::ISR,
        Country::JPN,
        Country::JOR,
        Country::KAZ,
        Country::KGZ,
        Country::KWT,
        Country::LAO,
        Country::LBN,
        Country::MYS,
        Country::MDV,
        Country::MNG,
        Country::MMR,
        Country::NPL,
        Country::OMN,
        Country::PAK,
        Country::PSE,
        Country::QAT,
        Country::SGP,
        Country::LKA,
        Country::SYR,
        Country::TWN,
        Country::TJK,
        Country::THA,
        Country::TUR,
        Country::TKM,
        Country::UZB,
        Country::VNM,
        Country::YEM,
        Country::DZA,
        Country::AGO,
        Country::BEN,
        Country::BWA,
        Country::BFA,
        Country::BDI,
        Country::CPV,
        Country::CMR,
        Country::CAF,
        Country::TCD,
        Country::COM,
        Country::COG,
        Country::COD,
        Country::CIV,
        Country::DJI,
        Country::EGY,
        Country::GNQ,
        Country::ERI,
        Country::SWZ,
        Country::ETH,
        Country::GAB,
        Country::GMB,
        Country::GHA,
        Country::GIN,
        Country::GNB,
        Country::KEN,
        Country::LSO,
        Country::LBR,
        Country::LBY,
        Country::MDG,
        Country::MWI,
        Country::MLI,
        Country::MRT,
        Country::MUS,
        Country::MAR,
        Country::MOZ,
        Country::NAM,
        Country::NER,
        Country::NGA,
        Country::RWA,
        Country::STP,
        Country::SEN,
        Country::SYC,
        Country::SLE,
        Country::SOM,
        Country::ZAF,
        Country::SSD,
        Country::SDN,
        Country::TZA,
        Country::TGO,
        Country::TUN,
        Country::UGA,
        Country::ZMB,
        Country::ZWE,
        Country::AUS,
        Country::FJI,
        Country::KIR,
        Country::MHL,
        Country::FSM,
        Country::NRU,
        Country::NZL,
        Country::PLW,
        Country::PNG,
        Country::WSM,
        Country::SLB,
        Country::TON,
        Country::TUV,
        Country::VUT,
    ];

    pub fn to_id(self) -> i32 {
        Country::ALL.iter().position(|&x| x == self).unwrap_or(0) as i32 + 1
    }

    pub fn from_id(id: i32) -> Option<Self> {
        Country::ALL.get((id - 1) as usize).copied()
    }

    pub fn get_value(self) -> Box<str> {
        format!("{self:?}").into_boxed_str()
    }
}

// Implement Type trait to tell SQLx how to handle this type
#[cfg(feature = "ssr")]
impl Type<Sqlite> for Country {
    fn type_info() -> SqliteTypeInfo {
        <i32 as Type<Sqlite>>::type_info()
    }
}

// Implement Encode to convert enum to database value
#[cfg(feature = "ssr")]
impl<'q> Encode<'q, Sqlite> for Country {
    fn encode_by_ref(
        &self,
        buf: &mut <Sqlite as sqlx::Database>::ArgumentBuffer<'q>,
    ) -> Result<sqlx::encode::IsNull, sqlx::error::BoxDynError> {
        <i32 as Encode<Sqlite>>::encode_by_ref(&self.to_id(), buf)
    }
}

// Implement Decode to convert database value to enum
#[cfg(feature = "ssr")]
impl<'r> Decode<'r, Sqlite> for Country {
    fn decode(
        value: <Sqlite as sqlx::Database>::ValueRef<'r>,
    ) -> Result<Self, sqlx::error::BoxDynError> {
        let id = <i32 as Decode<Sqlite>>::decode(value)?;
        Self::from_id(id).ok_or_else(|| format!("Invalid Country id: {id}").into())
    }
}
