name: socios-peix
services:
  socios-peix:
    image: mariinkys/socios-peix:latest
    container_name: socios-peix
    cpu_shares: 128  
    deploy:
      resources:
        limits:
          memory: 1024M 
    environment:
      - DATABASE_URL=sqlite:/app/db/socios.db
    labels:
      icon: https://raw.githubusercontent.com/mariinkys/socios-peix/refs/heads/main/resources/SociosPeix.png 
    ports:
      - target: 8080
        published: "8080"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/socios-peix/db
        target: /app/db
    devices: []  # No devices passed to the container
    cap_add: []  # No additional capabilities required
    network_mode: bridge  # Use default Docker bridge network
    privileged: false  # Do not run in privileged mode

x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://raw.githubusercontent.com/mariinkys/socios-peix/refs/heads/main/resources/SociosPeix.png 
  index: /
  port_map: "8080"
  scheme: http
  store_app_id: socios-peix
  title:
    custom: SociosPeix